config/routes.rb
Localflows::Application.routes.draw do
  root 'flows#index'
  match 'auth/:provider/callback', to: "sessions#create", via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get]

  match 'search', to: "users#eventful", as: "search", via: [:get]

  match 'new', to: "users#new", as: "new", via: [:get]

  match 'invite', to: "users#invite", as: "invite", via: [:get]

  resources :users
 end

app/models/user.rb
class User < ActiveRecord::Base

    def self.from_omniauth(auth)
        user = find_or_initialize_by(gid: auth.uid)

        user.name = auth.extra.raw_info.name
        user.email = auth.extra.raw_info.email
        if auth.extra.raw_info.picture
        	user.image = auth.extra.raw_info.picture
        else
            user.image = "assets/placeholder.png"
        end

        user.gaccess = auth.credentials.token
        user.grefresh = auth.credentials.refresh_token
        user.gid = auth.uid

        user.save
        
        return user
    end

    def eventful
        @eventful ||= Eventful::API.new ENV['eventful_key']
    end

    def gclient(token)
    	@google ||= Google::APIClient.new
    	if token.nil?
    		@google.authorization.access_token = self.gaccess
    	else
    		@google.authorization.access_token = token
    	end
    	return @google
    end

    def gcal
    	@calendar ||= self.gclient(nil).discovered_api('calendar', 'v3')
    end

    def freebusy(start, offset, email)
    	user = User.where(email: email).first
      	begin
            result = self.gclient(user.gaccess).execute(
                api_method: self.gcal.freebusy.query,
                body: JSON.dump({
                    timeMin: start.to_datetime.iso8601,
                    timeMax: (start + offset * 1800).to_datetime.iso8601,
                    items: [ { id: user.email} ]
                }),
                headers: {'Content-Type' => 'application/json'}
            )
	      	fb = { info: { email: user.email, name: user.name, image: user.image }, busy: Array.new(offset, false) }
            result.data.calendars[user.email].busy.each do |event|
                pos = getPos(start, offset, event.start, event.end)
                unless pos.nil?
                    for i in pos[:startPos]..pos[:endPos]
                        fb[:busy][i] = true
                    end
                end
            end
            return fb
	    rescue
            refresh = HTTParty.post('https://accounts.google.com/o/oauth2/token', {
                body: {
                    client_id: ENV["google_key"],
                    client_secret: ENV["google_secret"],
                    refresh_token: user.grefresh,
                    grant_type: "refresh_token"
                }
            })
            user.gaccess = refresh.parsed_response["access_token"]
            user.save
            result = self.gclient(user.gaccess).execute(
                api_method: self.gcal.freebusy.query,
                body: JSON.dump({
                    timeMin: start.to_datetime.iso8601,
                    timeMax: (start + offset * 1800).to_datetime.iso8601,
                    items: [ { id: user.email} ]
                }),
                headers: {'Content-Type' => 'application/json'}
            )
            fb = { info: { email: user.email, name: user.name, image: user.image }, busy: Array.new(offset, false) }
            result.data.calendars[user.email].busy.each do |event|
                pos = getPos(start, offset, event.start, event.end)
                unless pos.nil?
                    for i in pos[:startPos]..pos[:endPos]
                        fb[:busy][i] = true
                    end
                end
            end
            return fb
	    end
    end

    def group(min, max, emails, events)
    	start = min.to_time

        ## Integer((max.tomorrow.to_time - min.to_time) is in seconds
    	offset = Integer((max.tomorrow.to_time - min.to_time) / 1800)
    	
        # append user's own email
        emails << self.email

        # getting current user and all emails' free/busy values
    	all = {}

        # all[user_email] = freebusy(start, offset, email)

    	emails.each do |email|
    		all[email] = freebusy(start, offset, email)
    	end

        finalEvents = []
        newEvents = self.prune(events)
    	newEvents.each do |event|
    		s = event["start_time"]
    		e = event["stop_time"].nil? ? event["start_time"] + 3600 * 3 : event["stop_time"]
    		pos = getPos(start, offset, s, e)

    		if pos
		    	available = []
	    		emails.each do |email|
	    			a = false
	    			for i in pos[:startPos]..pos[:endPos]
	    				a = a || all[email][:busy][i]
	    			end
	    			unless a
	    				available << all[email][:info]
	    			end

	    		end
           #      me = false
           #      available.each do |email|
           #          if email[:email] == self.email
           #              me = true
           #          end
           #      end
           #      if me && available.length > 1
    	    		# event["available"] = available
           #          finalEvents << event
           #      end

                if available.length == emails.length
                    event["available"] = available
                    finalEvents << event
                end
	    	end
    	end

        # raise
        

    	return finalEvents.sort_by { |event| event["available"].length }.reverse
    end

    def getPos(start, offset, s, e)
    	if(s.to_time < start || e.to_time > (start + offset * 1800))
    		return nil
    	else
    		startPos = Integer((s.to_time - start) / 1800)
    		endPos = (e.to_time - start) / 1800
    		if(endPos - Integer(endPos) == 0)
	    		endPos = Integer(endPos) - 1
	    	else
	    		endPos = Integer(endPos)
	    	end
	    	return {startPos: startPos, endPos: endPos}
    	end
    end

    def prune(events)
    	fields = ["title", "start_time", "stop_time", "url", "description", "venue", "image"]
    	newEvents = []
    	events.each do |event|
    		if(event["stop_time"].nil? || !event["stop_time"].nil? && event["start_time"].strftime("%D") == event["stop_time"].strftime("%D"))
    			newEvent = {}
    			fields.each do |field|
    				if(field == "venue")
    					newEvent[field] = "#{event['venue_name']}<br />#{event['venue_address']}<br />#{event['city_name']}, #{event['region_abbr']}"
    					if event['postal_code']
    						newEvent[field] += " #{event['postal_code']}"
    					end
    				elsif field == "image"
                        if event["image"].nil?
                            newEvent[field] = "assets/placeholder.png"
                        else
                            newEvent[field] = event["image"]["medium"]["url"]
                        end
                    else
    					newEvent[field] = event[field]
    				end
    			end
    			newEvents << newEvent
    		end
    	end
    	return newEvents
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_filter :authenticated, except: [:new]

    def new
        redirect_to "/auth/google?origin=#{params[:city]},#{params[:state]}"
    end

    def index
      @users = User.all
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @users }
        format.json  { render :json => @users.map(&:attributes) }
      end
    end

    def edit
        @user = current_user
        redirect_to :root
    end

    def update
        user = current_user

        user.save

        redirect_to :root
    end

    def current_emails
        @emails = params[:search][:users].scan(/\((.+?)\)/).collect {|x| x[0] }
    end

    def eventful
        timeframe = params[:timeframe][:start].delete('-') +
                    '00-' + params[:timeframe][:end].delete('-') + '00'

        # emails = params[:search][:users].scan(/\((.+?)\)/).collect {|x| x[0] }

        @nFriends = current_emails.length + 1

        events = current_user.eventful.call('events/search', {
            date: timeframe,
            location: "#{params["search"]["city"]}, #{params["search"]["state"]}",
            page_size: 100,
            sort_order: "popularity",
            keywords: params[:search][:keyword]
        })["events"]

        if(events.nil?)
            @events = nil
        else
            @events = current_user.group(Date.parse(params[:timeframe][:start]), Date.parse(params[:timeframe][:end]), current_emails, events["event"])
        end
    end

    def invite
        confirm_event(params[:emails])
        redirect_to :root, notice: "Invitations successfully sent!"
    end

    ## this action will send an email through event_confirmation mailer
    ## it will be linked to from the page listing search results
    def confirm_event(current_emails)
        current_emails.each do |email|
            # raise
            UserMailer.event_confirmation(current_user, params["event-title"], params["event-description"], email).deliver

        end
    end
end

app/views/users/eventful.html.erb
<section class="mainbox">
    <%= render 'flows/user' %>
    <% if !@events.nil? %>
        <div class="datebox"><p class="resultboxtext">
            Your Adventures in <%= "#{params["search"]["city"]}, #{params["search"]["state"]}" %>
        </p></div>
        <% @events.each do |event|%>
            <div class="datebox eventbox">
                <article class="event">
                    <p class="title"><a href="<%= event["url"] %>" target="_blank"><%= event["title"] %></a></p>
                    <a href="<%= event["url"] %>" target="_blank"><img class="eventimg" src="<%= event['image'] %>" /></a>
                    <p class="venue"><%= event["venue"].html_safe %></p>
                    <p class="time"><%= event["start_time"].strftime("%A, %B %e, %Y, %H:%M%p") %>
                        <% unless event["stop_time"].nil? %>
                            <%= " to " + event["stop_time"].strftime("%A, %B %e, %Y, %H:%M%p") %>
                        <% end %>
                    </p>
                    <p class="description">
                        <% if event["description"].nil? %>
                            No description available.
                        <% else %>
                            <%= event["description"].html_safe %>
                        <% end %>
                    </p>
                    <%= form_tag(invite_url, :method => :get) do %>
                        <div class="friend-images">
                            <p class="availability alert alert-success"><%= "#{event['available'].length}/#{@nFriends}" %></p>
                            <% event["available"].each do |avail| %>
                                <img src="<%= avail[:image] %>" class="profile-pic">
                                <%= hidden_field_tag "emails[]", avail[:email] %>
                            <% end %>
                        </div>
                        <%= button_tag "Invite Available Friends", action: "invite", controller: "users", class: "btn btn-success signupbutton invitebutton" %>

                        <%= hidden_field_tag "event-title", event["title"] %>
                        <%= hidden_field_tag "event-description", event["description"] %>

                    <% end %>
                    
                </article>
            </div>
        <% end %>
    <% else %>
        <div class="datebox"><p class="resultboxtext">No events found.</p></div>
    <% end %>
</section>

app/views/users/index.html.erb
<%= @users %>